### PR TITLE
Fix error boundary Page link

### LINKED ISSUE #2109: Home link in "uh-oh" page doesn't work in app mode
When in the desktop app, if the "Uh-oh" page is shown, the "Get back home" link doesn't work. On Mac it reportedly tries to open the link in Finder, and on WSL it does nothing (likely tries to open the link but fails).

This means that users hitting this problem cannot navigate away from this page.

Let's do two things:
- [ ] Fix home link in app
- [ ] Add an app menu to navigate home
- [ ] Add back/forward app menus to navigate history

### PR DESCRIPTION
**Pull request by ashu8912**
fixes #2109 

- [x] Fix home link in app
- [x] Add an app menu to navigate home
- [x] Add back/forward app menus to navigate history

### CODE REVIEW

File: app/electron/main.ts [hunk 1]
```diff
@@ -319,6 +344,14 @@ function getDefaultAppMenu(): AppMenu[] {
           role: 'forcereload',
           id: 'original-force-reload',
         },
+        {
+          label: i18n.t('Go To Home Screen'),
```
Comment (joaquimrocha) [inline app/electron/main.ts:348]: Maybe just "Go to Home".

Comment (joaquimrocha) [reply app/electron/main.ts:348]: Or maybe we could have a new menu, with the options:
```
Navigate
  Reload
  Go to Home
  Go Back
  Go Forward
```

Here is an example on how to add the back/forward:
https://www.electronjs.org/docs/latest/api/browser-window#event-app-command-windows-linux

**Review by joaquimrocha — CHANGES_REQUESTED** [review]

File: app/electron/main.ts (hunk 1 above)
Comment (ashu8912) [reply app/electron/main.ts]: done

File: app/electron/main.ts [hunk 2]
```diff
@@ -319,6 +344,30 @@ function getDefaultAppMenu(): AppMenu[] {
...
+          role: 'homescreen',
+          id: 'original-home-screen',
+          click: () => {
+            mainWindow?.loadURL(startUrl);
+          },
+        },
+        {
+          label: i18n.t('Go Back'),
+          role: 'back',
+          id: 'original-back',
```
Comment (joaquimrocha) [inline app/electron/main.ts:358]: It would be nice if this and the Go Forward were disabled when there's no way to go back/forward. This has to be done by responding to a webContents event, then fetching the menus by ID and setting them as not enabled.

File: app/electron/main.ts [hunk 3]
```diff
@@ -319,6 +344,30 @@ function getDefaultAppMenu(): AppMenu[] {
           role: 'forcereload',
           id: 'original-force-reload',
         },
+        {
```
Comment (joaquimrocha) [inline app/electron/main.ts:347]: The new menus items should be in a new top menu "Navigate".
We should move the Reload there too. So in the end we get:
```
Navigate
  Reload
  separator
  Go to Home
  Go Back
  Go Forward
```

File: app/electron/main.ts [hunk 4]
```diff
@@ -319,6 +344,30 @@ function getDefaultAppMenu(): AppMenu[] {
...
+          click: () => {
+            mainWindow?.loadURL(startUrl);
+          },
+        },
+        {
+          label: i18n.t('Go Back'),
+          role: 'back',
+          id: 'original-back',
+          click: () => {
+            mainWindow?.webContents.goBack();
```
Comment (joaquimrocha) [inline app/electron/main.ts:360]: Check if the webContents can go back before you call this function.

File: app/electron/main.ts [hunk 5]
```diff
@@ -319,6 +344,30 @@ function getDefaultAppMenu(): AppMenu[] {
...
+          },
+        },
+        {
+          label: i18n.t('Go Forward'),
```
Comment (joaquimrocha) [inline app/electron/main.ts:364]: We should add an accelerator: Alt+Right
(and whatever it is in Mac)

File: app/electron/main.ts [hunk 6]
```diff
@@ -319,6 +344,30 @@ function getDefaultAppMenu(): AppMenu[] {
...
+        {
+          label: i18n.t('Go To Home'),
+          role: 'homescreen',
+          id: 'original-home-screen',
+          click: () => {
+            mainWindow?.loadURL(startUrl);
+          },
+        },
+        {
+          label: i18n.t('Go Back'),
```
Comment (joaquimrocha) [inline app/electron/main.ts:356]: We should add an accelerator: Alt+Left
(and whatever it is in Mac)

**Review by joaquimrocha — CHANGES_REQUESTED** [review]
Please check my comments, which I think improve the UX.

File: app/electron/main.ts [hunk 7]
```diff
@@ -319,6 +344,30 @@ function getDefaultAppMenu(): AppMenu[] {
           role: 'forcereload',
           id: 'original-force-reload',
         },
+        {
+          label: i18n.t('Go To Home'),
```
[the remark this answers is not in the document]
Comment (ashu8912) [reply app/electron/main.ts]: done

File: app/electron/main.ts (hunk 2 above)
Comment (ashu8912) [reply app/electron/main.ts:404]: done

File: app/electron/main.ts (hunk 3 above)
Comment (ashu8912) [reply app/electron/main.ts:393]: done

File: app/electron/main.ts (hunk 4 above)
Comment (ashu8912) [reply app/electron/main.ts:408]: done

File: app/electron/main.ts (hunk 5 above)
Comment (ashu8912) [reply app/electron/main.ts:412]: done

File: app/electron/main.ts (hunk 6 above)
Comment (ashu8912) [reply app/electron/main.ts:402]: done

File: frontend/src/components/App/Layout.tsx [hunk 8]
```diff
@@ -47,7 +47,7 @@ function ClusterNotFoundPopup() {
       alignItems="center"
     >
       <Box p={0.5}>{t(`Something went wrong with cluster {{ cluster }}`, { cluster })}</Box>
-      <Button variant="contained" size="small" href="/">
+      <Button variant="contained" size="small" href={window.desktopApi ? '#' : '/'}>
```
Comment (joaquimrocha) [inline frontend/src/components/App/Layout.tsx:50]: Hmm, can you add the fixes as a different commit? Sorry I didn't ask for this before.

File: app/electron/main.ts [hunk 9]
```diff
@@ -348,6 +380,46 @@ function getDefaultAppMenu(): AppMenu[] {
...
+          id: 'original-home-screen',
+          click: () => {
+            mainWindow?.loadURL(startUrl);
+          },
+        },
+        {
+          label: i18n.t('Go Back'),
+          role: 'back',
+          id: 'original-back',
+          accelerator: getAcceleratorForPlatform('Alt+Left', 'Cmd+Left', 'Alt+Left'),
```
Comment (joaquimrocha) [inline app/electron/main.ts:405]: I'd prefer to call this function with only one param: Left | Right. Then inside the function should decide what to output.
Also, did you verify if Option+Left works on Mac? See:
https://www.electronjs.org/docs/latest/api/accelerator/#platform-notice
https://support.apple.com/guide/safari/keyboard-and-other-shortcuts-cpsh003/mac (it says it's `Command+[`)

**Review by joaquimrocha — CHANGES_REQUESTED** [review]
Works fine but I think we can improve the code a bit. Please check my comments.

File: frontend/src/components/App/Layout.tsx (hunk 8 above)
Comment (ashu8912) [reply frontend/src/components/App/Layout.tsx:50]: but this is a different commit @joaquimrocha

File: app/electron/main.ts (hunk 9 above)
Comment (ashu8912) [reply app/electron/main.ts]: updated, thanks @joaquimrocha

**Review by joaquimrocha — APPROVED** [review]
