### PR TITLE
Kubeconfig refresh

### LINKED ISSUE #322: Re-read the kubeconfig file when needed
## Current situation

If we have Headlamp (desktop) running and change the kubeconf file, e.g. to add, remove, or change a cluster, then Headlamp will not be aware of it until it is reloaded.

## Impact

If users want to add a new cluster and see it reflected in Headlamp, they cannot do so until they restart the program. Moreover, they are not even warned that they need to restart Headlamp.
Another related issue is that e.g. if Minikube is configured but not started, and we start Headlamp before starting Minikube, then the connections to Minikube will fail even after Minikube has been started.

## Ideal future situation

There is a way to quickly reflect the changes made to kubeconfig, in a running Headlamp.

## **Implementation options

We should detect changes to the kubeconfig file and display the reload banner+button (I believe we already have a similar banner related to internet connection outage). Upon clicking the reload button, the backend should re-read the kubeconfig.

## Additional information

This should be implemented only in the desktop version.

### PR DESCRIPTION
**Pull request by yolossn**
Fixes #322

### CODE REVIEW

File: frontend/src/components/App/Layout.tsx [hunk 1]
```diff
@@ -44,11 +54,134 @@ const useStyle = makeStyles(theme => ({
 
 export interface LayoutProps {}
 
+const CLUSTER_FETCH_INTERVAL = 5 * 1000; // ms
```
Comment (yolossn) [inline frontend/src/components/App/Layout.tsx:57]:
```suggestion
const CLUSTER_FETCH_INTERVAL = 10 * 1000; // ms
```

**Review by illume — CHANGES_REQUESTED** [review]
Could you please add a test for the golang part, and a story for the react component?

File: frontend/src/components/App/Layout.tsx [hunk 2]
```diff
@@ -44,11 +54,133 @@ const useStyle = makeStyles(theme => ({
...
+          dispatch(setConfig(configToStore));
+        } else {
+          Object.keys(clustersToConfig).every((key: string) => {
+            const clustersCopy = _.cloneDeep(clusters[key]);
+            // remove the cluster status from the comparison
+            delete clustersCopy.useToken;
+            if (_.isEqual(clustersCopy, clustersToConfig[key])) {
+              return true;
+            } else {
+              dispatch(setConfig(configToStore));
```
Comment (illume) [inline frontend/src/components/App/Layout.tsx:167]: It seems this would dispatch multiple times if there are multiple changes, but we probably only want to dispatch once when multiple ones have changed?

File: frontend/src/components/App/Layout.tsx [hunk 3]
```diff
@@ -44,11 +54,133 @@ const useStyle = makeStyles(theme => ({
...
+    );
+    fetchConfig();
+    return () => {
+      if (window.clusterConfigFetchHandler) {
+        clearInterval(window.clusterConfigFetchHandler);
+      }
+    };
+  }, []);
+
+  const fetchConfig = () => {
```
Comment (illume) [inline frontend/src/components/App/Layout.tsx:142]: This function could use documentation about what/why it's doing.

File: frontend/src/components/App/Layout.tsx [hunk 4]
```diff
@@ -44,11 +54,133 @@ const useStyle = makeStyles(theme => ({
...
 export default function Layout({}: LayoutProps) {
   const classes = useStyle();
   const arePluginsLoaded = useTypedSelector(state => state.ui.pluginsLoaded);
-
+  const dispatch = useDispatch();
+  const clusters = useTypedSelector(state => state.config.clusters);
   const { t } = useTranslation('frequent');
+  const [isClusterNotAvailable, setIsClusterNotAvailable] = useState(false);
+
+  useEffect(() => {
```
Comment (illume) [inline frontend/src/components/App/Layout.tsx:126]: Probably all of this new logic should go into it's own component. New components should go into their own file named after the component. In this case it would make sense if all the related parts are in components inside a folder of components, and then only one component is imported and used. So that all the pieces implementing this feature are together in one place.

File: backend/cmd/headlamp.go [hunk 5]
```diff
@@ -94,9 +93,18 @@ type spaHandler struct {
...
+	DynamicCluster
+	InCluster
+)
+
+// Source indicates if the context proxy is for a cluster
+// configured from kubeconfig or dynamic cluster or incluster.
 type contextProxy struct {
 	context *Context
 	proxy   *httputil.ReverseProxy
+	source  int
```
Comment (illume) [inline backend/cmd/headlamp.go:107]: Usually the documentation for a field would come after the field.

```golang
source   int // If the context proxy is ...
```

File: frontend/src/components/App/Layout.tsx [hunk 6]
```diff
@@ -44,11 +54,133 @@ const useStyle = makeStyles(theme => ({
...
+  const cluster = getCluster();
+  const { t } = useTranslation('frequent');
+  const isSidebarOpen = useTypedSelector(state => state.ui.sidebar.isSidebarOpen);
+  const history = useHistory();
+
+  if (!cluster) {
+    return null;
+  }
+
+  if (!isClusterNotAvailable) {
```
Comment (joaquimrocha) [inline frontend/src/components/App/Layout.tsx:78]: Nit: You could condense this as `!cluster || !isClusterNotAvailable`.

File: frontend/src/components/App/Layout.tsx [hunk 7]
```diff
@@ -44,11 +54,133 @@ const useStyle = makeStyles(theme => ({
...
+    return null;
+  }
+  return (
+    <>
```
Comment (joaquimrocha) [inline frontend/src/components/App/Layout.tsx:82]: AFAIU, you don't need the fragment here since you only have one element (Box) inside it.

File: frontend/src/components/App/Layout.tsx [hunk 8]
```diff
@@ -44,11 +54,133 @@ const useStyle = makeStyles(theme => ({
...
+          color={'error.main'}
+          bgcolor={theme.palette.common.white}
+          ml={1}
+          p={0.5}
+          onClick={() => {
+            history.replace('/');
+            changeClusterNotAvailableStateHandler(false);
+          }}
+        >
+          {t('frequent| Take me to cluster chooser')}
```
Comment (joaquimrocha) [inline frontend/src/components/App/Layout.tsx:111]: You don't need the `frequent` here, since it's the default namespace when you declared the `useTranslation`. If you keep this, please remove the space after the pipe.

File: frontend/src/components/App/Layout.tsx [hunk 9]
```diff
@@ -44,11 +54,133 @@ const useStyle = makeStyles(theme => ({
...
+          textAlign: 'center',
+        }}
+        bgcolor={'error.main'}
+        zIndex={1400}
+        width={'100%'}
+        p={0.5}
+        alignItems="center"
+      >
+        <Box ml={isSidebarOpen ? '-25vw' : 0}>
+          {t(`Something went wrong with cluster ${cluster}`)}
```
Comment (joaquimrocha) [inline frontend/src/components/App/Layout.tsx:98]: Should be
```
          {t(`Something went wrong with cluster {{ cluster }}`, {cluster})}
```

File: frontend/src/components/App/RouteSwitcher.tsx [hunk 10]
```diff
@@ -44,8 +44,10 @@ export default function RouteSwitcher() {
             requiresAuth={!route.noAuthRequired}
             requiresCluster={getRouteUseClusterURL(route)}
             exact={!!route.exact}
-            children={<RouteComponent route={route} />}
-            key={index}
+            clusters={useClustersConf()}
```
Comment (joaquimrocha) [inline frontend/src/components/App/RouteSwitcher.tsx:47]: This is a hook, so be careful if it's being used conditionally here (hooks must be used conditionally). Maybe bring it earlier in the component's code.

**Review by joaquimrocha — CHANGES_REQUESTED** [review]

File: backend/cmd/kubeconfig.go [hunk 11]
```diff
@@ -123,3 +128,127 @@ func GetOwnContext(config *HeadlampConfig) (*Context, error) {
...
+		log.Println("Error watching for kube config changes:", err)
+		return
+	}
+	defer watcher.Close()
+
+	done := make(chan bool)
+
+	ticker := time.NewTicker(tickerDuration)
+
+	err = watcher.Add(path)
```
[the remark this answers is not in the document]
Comment (yolossn) [reply backend/cmd/kubeconfig.go:217]: Aah, good catch. Ill make the changes

File: backend/cmd/kubeconfig.go [hunk 12]
```diff
@@ -123,3 +128,127 @@ func GetOwnContext(config *HeadlampConfig) (*Context, error) {
...
+	if err != nil {
+		log.Printf("Couldn't add %s to watcher: %v", path, err)
+	}
+
+	go func() {
+		for {
+			select {
+			// when the kubeconfig file is removed the watcher stops listening
+			// so this is a workaround to check if the file exists and add it to the watcher
```
[the remark this answers is not in the document]
Comment (yolossn) [reply backend/cmd/kubeconfig.go:226]: This cant be added when using the `fsnotify.Rename` or `fsnotify.Remove` event because the file is automatically removed from the watcher when the file is removed so we won't get those events in the first place.

File: frontend/src/components/App/Layout.tsx (hunk 3 above)
Comment (ashu8912) [reply frontend/src/components/App/Layout.tsx:141]: added a comment about what it does

File: frontend/src/components/App/Layout.tsx (hunk 4 above)
Comment (ashu8912) [reply frontend/src/components/App/Layout.tsx:121]: umm i am not sure if we want to create a new component out of this, the new addition just add a new fetchConfig function and passes new set of state to the already present RouteSwitcher component

File: frontend/src/components/App/Layout.tsx (hunk 6 above)
Comment (ashu8912) [reply frontend/src/components/App/Layout.tsx]: updated

File: frontend/src/components/App/Layout.tsx (hunk 8 above)
Comment (ashu8912) [reply frontend/src/components/App/Layout.tsx]: updated

File: frontend/src/components/App/Layout.tsx (hunk 9 above)
Comment (ashu8912) [reply frontend/src/components/App/Layout.tsx]: fixed

File: frontend/src/components/App/RouteSwitcher.tsx (hunk 10 above)
Comment (ashu8912) [reply frontend/src/components/App/RouteSwitcher.tsx]: fixed, thanks

File: frontend/src/components/App/Layout.tsx [hunk 13]
```diff
@@ -44,11 +54,136 @@ const useStyle = makeStyles(theme => ({
...
+      () => {
+        fetchConfig();
+      },
+      CLUSTER_FETCH_INTERVAL,
+      clusters
+    );
+    fetchConfig();
+    return () => {
+      if (window.clusterConfigFetchHandler) {
+        clearInterval(window.clusterConfigFetchHandler);
```
Comment (joaquimrocha) [inline frontend/src/components/App/Layout.tsx:132]: I think this variable should be reset in moment, to avoid future misinterpretations.

File: frontend/src/components/App/Layout.tsx [hunk 14]
```diff
@@ -44,11 +54,136 @@ const useStyle = makeStyles(theme => ({
...
+            const clustersCopy = _.cloneDeep(clusters[key]);
+            // remove the cluster status from the comparison
+            delete clustersCopy.useToken;
+            if (_.isEqual(clustersCopy, clustersToConfig[key])) {
+              return true;
+            } else {
+              isConfigDifferent = true;
+              return false;
+            }
+          });
```
Comment (joaquimrocha) [inline frontend/src/components/App/Layout.tsx:170]: This could be abstracted into its own function (e.g. `isClustersConfigDifferent(clusters, newClusters)`), to make it simpler to understand.

File: backend/cmd/kubeconfig.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (joaquimrocha) [reply backend/cmd/kubeconfig.go]: So when does these triggers happen? Maybe they're happening for directories only?

**Review by joaquimrocha — CHANGES_REQUESTED** [review]

**Comment by yolossn** [comment]
> So when does these triggers happen? Maybe they're happening for directories only?

The trigger is a 10 second ticker, every ten seconds the number of files being watched and the no of files in the config is compared it the no of files is less then the files are added to the watcher again.

**Comment by joaquimrocha** [comment]
@yolossn , I have added a fixup commit that fixes 4 things:
    1. Corrects the translations' namespace;
    2. A bug when the clusters change in the config but the list has the same length (happens when replacing a cluster or renaming one)
    3. Avoids deep-cloning the cluster info when the useToken is not used.
    4. Improves the error banner: Replaces a clickable Box by an actual Button (important for the UI + a11y), disregards the sidebar in order to fix the alignment of the text, since the route is moved to login and in there there's no sidebar anyway.

Please review/test to see if it's all good.

**Comment by yolossn** [comment]
Thanks for improvements.
Tested it and found that the Error banner is visible even when the cluster exists in the `/config` response
image

File: backend/cmd/kubeconfig.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (yolossn) [reply backend/cmd/kubeconfig.go]: Discussed this privately and updated the comment to make it clear.

**Comment by yolossn** [comment]
I fixed the Error banner issue. Can someone test and review the changes? cc: @joaquimrocha @ashu8912

**Comment by joaquimrocha** [comment]
This is working pretty well and is very useful. Thanks!
